defaults:
  - _self_
  - ../general_prompts@general_prompts: three_choice_entailment

name: anli
category:
  - NLI

preprocessor:
  name: "three_choice_entailment"
  choices: null
  choice_str: null
  mcq_choice_str: null
  classification_template: null
  premise_template: null
  hypothesis_template: null
  question_template: null
  context_template: null
