defaults:
  - _self_
  - ../general_prompts@general_prompts: three_choice_entailment
name: cb
verbose_name: CommitmentBank
parent_dataset: super_glue
category:
  - NLI

preprocessor:
  name: "anli"
  choices: null
  choice_str: '"yes", "no", or "maybe"'
  mcq_choice_str: 'a) yes\nb) no\nc) maybe'