defaults:
  - _self_

default_answer_choices:
  - Yes
  - Maybe
  - No

name: cb
verbose_name: CommitmentBank
dir_name: cb
parent_dataset: super_glue
category:
  - NLI

preprocessor:
  name: "three_choice_entailment"
  choices: null
  choice_str: null
  mcq_choice_str: null
  classification_template: null
  premise_template: null
  hypothesis_template: null
  question_template: null
  context_template: null