defaults:
  - _self_

name: craigslist_bargains
dir_name: craigslist_bargains
category:
  - Dialogue

preprocessor:
  name: "craigslist"
  add_speaker_prefix: false
  choices: null


splits:
  - validation
