defaults:
  - _self_

default_answer_choices:
  - yes
  - no

name: rte
verbose_name: RecognizingTextualEntailment
parent_dataset: super_glue
dir_name: rte
category: NLI

preprocessor:
  name: "two_choice_entailment"
  choices: null
  choice_str: null
  mcq_choice_str: null
  classification_template: null
  premise_template: null
  hypothesis_template: null
  question_template: null
  context_template: null