defaults:
  - _self_
  - task: ???

force: True
model_name: "t5-small"
batch_size: 2
num_proc: 4
split: ???
run_name: ???
cuda_device: 0
disable_caching: False
prompt_count: null

debug: False
disable_tracking: False

prompt_experiment_mode: default
prompt_path: null

group:
  override_name: null
  suffix: null

evaluation:
  force_generation: False
  length_normalization: False
  use_only_correct_choice: False
  lowercase_choices: False

general_prompts:
  dir: prompts
  category_filter: null
  answer_filter: null

prompt_filter:
  name_list: null
  choice_list: null
  choices_in_prompt: null
  original_task: null

hydra:
  run:
    dir: outputs/${task.name}.${split}