defaults:
  - _self_
  - task: ???

force: True
model_name: "t5-small"
batch_size: 8
beams: 1
force_generation: False
disable_tracking: False
length_normalization: False
num_proc: 4
split: ???

debug: False
use_general_prompts: False

prompt_filter:
  name: null
  choice: null
  choices_in_prompt: null
  original_task: null

hydra:
  run:
    dir: outputs/${task.name}.${split}